### ISSUE TITLE
Can't pickle mongoengine.Document object

### ISSUE THREAD

**Issue by Uznick** [hmarr/mongoengine#135]
Django from trunk, last version of mongoengine.

I insert the object into session and get exception on session autosaving:

On autosaving the session I get

<pre>
Traceback:
File "/usr/local/var/pip/src/django/django/core/handlers/base.py" in get_response
  178.                 response = middleware_method(request, response)
File "/usr/local/var/pip/src/django/django/contrib/sessions/middleware.py" in process_response
  36.                 request.session.save()
File "/usr/local/Cellar/python/2.7.1/lib/python2.7/site-packages/mongoengine/django/sessions.py" in save
  49.         s.session_data = self.encode(self._get_session(no_load=must_create))
File "/usr/local/var/pip/src/django/django/contrib/sessions/backends/base.py" in encode
  93.         pickled = pickle.dumps(session_dict, pickle.HIGHEST_PROTOCOL)
File "/usr/local/Cellar/python/2.7.1/lib/python2.7/site-packages/pymongo/collection.py" in __call__
  967.                         self.__name.split(".")[-1])

Exception Type: TypeError at /create/
Exception Value: 'Collection' object is not callable. If you meant to call the '__getnewargs__' method on a 'Collection' object it is failing because no such method exists.
</pre>

The code my view.py is

<pre>
toolbar = ToolbarStep2Form(request.POST)
new_toolbar = toolbar.save()
request.session['u_new_toolbar'] = new_toolbar
</pre>

Form is created by django-mongoforms

**Comment by justquick** [comment]
what version of pymongo are you using? i think it might need updating...

**Comment by Uznick** [comment]
<pre>
>>> import pymongo
>>> pymongo.version
'1.9'
</pre>


<pre>
pip search pymongo
pymongo                   - Python driver for MongoDB <http://www.mongodb.org>
  INSTALLED: 1.9 (latest)
</pre>


Seems like everything is ok with pymongo version

**Comment by Uznick** [comment]
nope, pymongo is installed with pip, it's python that is installed with brew, but I tried:

<pre>
➜ uznick@Uznicks-Macbook-Pro ~/PycharmProjects/moikrieg/tmp rm -rf /usr/local/Cellar/python/2.7.1/lib/python2.7/site-packages/pymongo-1.9-py2.7.egg-info 
➜ uznick@Uznicks-Macbook-Pro ~/PycharmProjects/moikrieg/tmp pip install -e git+https://github.com/mongodb/mongo-python-driver.git#egg=pymongo  
...
    Creating /usr/local/Cellar/python/2.7.1/lib/python2.7/site-packages/pymongo.egg-link (link to .)
    Adding pymongo 1.9- to easy-install.pth file
    
    Installed /usr/local/var/pip/src/pymongo
Successfully installed pymongo
Cleaning up...
</pre>


And in the result -- the same exception :(

Hmmm... there was a comment up there some time before...

**Comment by justquick** [comment]
yup i removed it because i dont know whats going wrong. maybe Collections are not serialize-able or just missing some py magic like  ___getnewargs__?

**Comment by rozza** [comment]
Hi, I've added a test case in the dev branch, which shows pickling working as expected..

Please, reopen if you have a test case that disproves this!

**Comment by jschrewe** [comment]
I don't really understand why, but I can't pickle documents that have a a gridfs file associated with them. The error message is:

``````
  [ parts of a longer backtrace ]
  File "/usr/local/Cellar/python/2.7.1/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/Cellar/python/2.7.1/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/local/Cellar/python/2.7.1/lib/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/local/Cellar/python/2.7.1/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/usr/local/bin/../Cellar/python/2.7.1/lib/python2.7/copy_reg.py", line 84, in _reduce_ex
    dict = getstate()
  File "/usr/local/Cellar/python/2.7.1/lib/python2.7/site-packages/pymongo/collection.py", line 1160, in __call__
    self.__name.split(".")[-1])
TypeError: 'Collection' object is not callable. If you meant to call the '__getstate__' method on a 'Collection' object it is failing because no such method exists.```
``````

**Comment by rozza** [comment]
@jschrewe added #381
