### ISSUE TITLE
Authentication in a multi-threaded environment fails.

### ISSUE THREAD

**Issue by ghost** [hmarr/mongoengine#151]
Due to the use of the process ID as an identifier and not the process ID combined with thread ID.  The following patch corrects the issue.

<pre><code>diff --git a/mongoengine/connection.py b/mongoengine/connection.py
index 814fde1..2c873a6 100644
--- a/mongoengine/connection.py
+++ b/mongoengine/connection.py
@@ -1,4 +1,5 @@
 from pymongo import Connection
+import threading
 import multiprocessing

 **all** = ['ConnectionError', 'connect']
@@ -54,6 +55,7 @@ def _get_db(reconnect=False):
 def get_identity():
     identity = multiprocessing.current_process()._identity
     identity = 0 if not identity else identity[0]
-    identity = (identity, threading.current_thread().name)
   return identity
  
  def connect(db, username=None, password=None, **kwargs):
  </pre></code>

**Comment by marrow** [comment]
It took me four hours (it's now 4am) to track down the reason why I was getting authentication errors from MongoDB despite authenticating correctly and all my small-scale tests (identical web framework configuration loaded into a ipython shell and direct mongo shell) working flawlessly.

Diagnosed using MongoDB's HTTP interface (I noticed additional connections appearing despite only one value in mongoengine.connection._connection and _db) and with the help of the third note from [pymongo's documentation on `.authenticate()`](http://api.mongodb.org/python/1.9%2B/api/pymongo/database.html#pymongo.database.Database.authenticate).

**Comment by amcgregor** [comment]
This issue continues to effect me (was accidentally logged in as marrow) in my production deployments of Contentment, a MongoEngine + WebCore (web framework) content management system.

**Comment by colinhowe** [comment]
Sorry to reopen this one but I think the fix has a bug in it. PyMongo handles connection pooling for threads automatically. This code will cause a pool _per thread_ without a good reason. Further, the pool won't be freed when the thread dies unless the developer realises this will happen and starts grubbing around in here.

The fix is fairly simple. Just change is so that connections are done using process identity and auth is done using process+thread identity.

There's a diff here that does it (and we're now using in production quite happily). https://github.com/colinhowe/mongoplan/commit/b49ce007b226f9335edc7116e19a98f88452da8f#diff-1

It's on a fork of MongoEngine that I have no intention of merging back in as I'm going to be changing it pretty drastically to suit my own needs :)

**Comment by rozza** [comment]
Hi @colinhowe the connection class has now changed massively to support multidb (dev/0.6) and to use pymongo's connection pooling.  So this will be a non issue.
