### ISSUE TITLE
queryset limit or [:10] slicing does not work as expected

### ISSUE THREAD

**Issue by ozexpert** [hmarr/mongoengine#166]
I have a queryset like this in python.

notes = Note.objects[:10]

if i do len(notes) it gives me 10 which is correct. But when i pass "notes" object to template and try

{{notes|length}} 

then i get 16 (which is total count of note data). Even if i do Note.objects.limit(5) it's the same. Is this a bug in MongoEngine? or am i doing something wrong?

**Comment by rozza** [comment]
I take it this is in a django template?  This is weird as all the default length filter just does is return len(value).

**Comment by ozexpert** [comment]
yeah. in django template. In python shell, it works as is.

**Comment by ozexpert** [comment]
does any one know how i can solve this and if there is a workaround please let me know.

**Comment by rozza** [comment]
I created a test case that passes against the dev branch:  https://gist.github.com/978162
This was fixed in: https://github.com/hmarr/mongoengine/commit/18baa2dd7a4e909169b694cb6ec36214c5a51506 so I have merged that commit into master: 

https://github.com/hmarr/mongoengine/commit/378b52321bd428ae40335ca5e73b9295049da95a

Should all be fine now ozexpert

**Comment by ozexpert** [comment]
Thanks! do you know when's the next release of MongoEngine?

**Comment by Pentusha** [comment]
Same problem at 0.8.0+
