### ISSUE TITLE
validate for non required fields

### ISSUE THREAD

**Issue by wpjunior** [hmarr/mongoengine#197]
be a example

``` python
desc = StringField(required=False)
desc.validate(None) #raises a exception

desc = StringField(required=True)
desc.validate(None) # be raises "This fiels is required"
```

see my commit for this issue:
https://github.com/wpjunior/mongoengine/commit/2ece0bc6854da7363711c5828f84c0798574645e

**Comment by rozza** [comment]
I'm not sure I agree as None is not a valid value for a StringField and therefore should throw a validation error.

What use case is this causing you an issue?
Also, there are no tests for your commit and can you add it as a pull request instead - its easier to merge...

**Comment by rozza** [comment]
Possible duplicate of #74

**Comment by wpjunior** [comment]
all fields that are not required as may have the value None

in other projets (django for example:)
see
https://code.djangoproject.com/browser/django/trunk/django/db/models/fields/__init__.py#L180

**Comment by rozza** [comment]
Sure in Django - whats your use case where this is broken?

**Comment by wpjunior** [comment]
in django-mongoforms when a field is not required validation is receiving incorrect because this function.

example:
integer, decimal field blank receives "argument must be a string or a number"

it validates using your method validation.

**Comment by rozza** [comment]
I'm not sure on the best solution here, mainly because I believe the validation behaviour is correct, None is not a valid string and changing it to say it is leads to unexpected behaviour.  Eg the value saved in the db would then be "None" as a string...

Possibly this issue should be fixed in: django-mongoforms and how it consumes mongoengine.

Document validation does take in field.required into consideration to validate the resultant document data and then save it.

Perhaps posting this on the email group may get more django / mongoforms users

**Comment by wpjunior** [comment]
I sent the fix for the mongoforms
thanks

**Comment by Uznick** [comment]
Actually, the same problem is with django-mongotools.
