### ISSUE TITLE
DetailView and Document

### ISSUE THREAD

**Issue by wpjunior** [hmarr/mongoengine#208]
``` python
from django.views.generic.detail import DetailView

class Moradia(Document):
    name = StringField()

class DetailMoradiaView(DetailView):
    model = Moradia

DetailMoradiaView.as_view()

raise this Error:
type object 'Moradia' has no attribute '_default_manager'

or

from django.views.generic.detail import DetailView

class Moradia(Document):
    name = StringField()

class DetailMoradiaView(DetailView):
    def get_queryset(self):
        return Moradia.objects

raises the error:
'dict' object has no attribute 'object_name'
```

**Comment by rozza** [comment]
I'd imagine you'd have to write your own generic views to work with mongoengine.

Django relies on its own ORM implementation and we don't share the same API.

If you create some generic views with tests I'd happily add them to the django part of the library.

**Comment by wpjunior** [comment]
In a few days I will be posting the MongoEngine Classes View :-)

**Comment by hrharkins** [comment]
After some quick looking around it appears that MongoEngine's use of _meta is in conflict with Django's.  Apparently Django uses _meta for its models and since MongoEngine uses it as a dict Django's getting confused.  One error specifically occurs under Django 1.4 at line 131 after is looks for a '_meta' attribute.  

This can be somewhat alleviated by explicitly overloading the get_template_names() and context_object_name members within the DetailView overloads (by app authors, not the library).  There are likely other cases as well that collide with _meta though, so if the library could use a different name then a lot of these errors might be avoided.
