### ISSUE TITLE
DictField default value should not be mutable?

### ISSUE THREAD

**Issue by seangh** [hmarr/mongoengine#46]
DictField default value (reference) can be incorrectly shared by other instances.
e.g.
class D(Document):
  data = DictField(default = {})

d1 = D()
d1.data['foo'] = 'bar'
d2 = D()
print d2.data  
=> {'bar':'foo'}

**Comment by flosch** [comment]
I commited some sort of a fix here: http://github.com/flosch/mongoengine/commit/51065e7a4dda96943dadfcbdfcca6111dfa1f9f5

Since DictField and ListField have a default empty value since some commits, there's no need to do it manually. I think my solution isn't that much nice as I wish but it still works. If you want to declare your own default value, you can pass an callable (e. g. a lambda) to the default argument. It's been called whenever MongoEngine creates a new field. 

Are there any other opinions of how to solve this kind of issue?

**Comment by hmarr** [comment]
Fixed {Dict,List}Field default issue. Closed by 3b62cf80cde0b83715662ce9bb01053dc13a7060.
