### ISSUE TITLE
primary key unique validation

### ISSUE THREAD

**Issue by jonhkr** [hmarr/mongoengine#461]
My 'User' document have the field 'login' as 'primary_key'
It should raise an OperationError when trying to save duplicated entries, but it doesn't.

**Comment by codeb2cc** [comment]
I think the problem is mongoengine try to update a document when it holds a primary_key(`_id`). When you try to save the 'duplicated entries', there's no error at the db level. Mongoengine just updates the one with the same primary_key.
In your case, set `force_insert` to True when try to save the document will solve the problem. It will correctly raise an `OperationError`.

Check https://github.com/hmarr/mongoengine/issues/268

**Comment by rozza** [comment]
Yeah, mongoDB will just save a document to the database - force_insert will do what you require.  In mongoDB and pymongo save() does an upsert if _id exists otherwise an insert.

Not sure the best way forward for this ticket and #268.

**Comment by jonhkr** [comment]
After some lost time trying to do this I decided to don`t use the login as primary_key, jus set it as unique, closing the issue, Many thanks
