### ISSUE TITLE
AttributeError triggering is weird

### ISSUE THREAD

**Issue by bastienlabelle** [hmarr/mongoengine#7]
Hi,

Let's admit I have this model:

```
class Person(Document):
    first_name = StringField(required=True)
    last_name = StringField()

>>> p = Person(first_name='Bastien')
>>> p.save()
>>> p.last_name
```

This code will produce an 

```
AttributeError: last_name
```

As it has been defined, shouldn't p.name be returning None, even if it has not been specified, instead of an Exception?

Because if an attribute is not required, the following code might be something like:

```
if p.last_name:
    print 'Hi %s %s' % (p.first_name, p.last_name)
else:
    print 'Hi %s' % (p.first_name)
```

If I want to do that with the current code, an Exception is raised. What do you think?

**Comment by hmarr** [comment]
I'm fine with changing this - I've seen some libraries that raise an exception in this case and some that don't; so far I've been using

```
if 'last_name' in p:
    do_stuff()
```

but returning None can make code a little neater in some cases (such as `author = comment.author or 'Anonymous'`) so I'll make the change to always return the default (which is None unless otherwise specified) if the value is not present.

On a side note, for your example `name` could be defined as a method or property on the `Person` class for convenience:

```
class Person(Document):
    first_name = StringField(required=True)
    last_name = StringField()

    @property
    def name(self):
        if self.last_name:
            return '%s %s' % (self.first_name, self.last_name)
        return self.first_name

>>> p = Person(first_name='Bastien')
>>> p.save()
>>> p.name
'Bastien'
>>> p.last_name = 'Smith'
>>> p.name
'Bastien Smith'
```

**Comment by bastienlabelle** [comment]
I think

```
if 'last_name' in p:
    ...
```

Makes sense for a dict, but as we are defining objects with explicit properties, I really think that

```
if p.last_name:
    ...
```

is more logical.

Thank you for your time :)
