### ISSUE TITLE
pymongo 1.9 compatibility

### ISSUE THREAD

**Issue by berinhard** [hmarr/mongoengine#76]
The new version of pymongo doesn't have the attribute dbref. I discovered that running some tests and the error happened at the file mongoengine/fields.py in line 388, for example.

AttributeError: 'module' object has no attribute 'dbref'

For the 1.8 version of pymongo it works correctly, but the 1.9 version was launched today (29/09/2010)!
http://pypi.python.org/pypi/pymongo/

**Comment by alefnula** [comment]
Submodules objectid, dbref, son, etc... are moved to bson module so the fix is either:

http://paste.pocoo.org/show/269227/

or:

http://paste.pocoo.org/show/269228/

I don't know if their intention is to leave this modules in pymongo or completely remove them one day?

[Edit: updated the patches, fist ones were not complete]

**Comment by hmarr** [comment]
Cheers for that - fixed in commit 3acfd907202afa4f2712
