### ISSUE TITLE
Multiple uses of unimported modules

### ISSUE THREAD

**Issue by agronholm** [hmarr/mongoengine#88]
I encountered this with MongoEngine v0.3, but looking at the source, I can see that it has not been fixed yet. At least fields.py uses several modules from pymongo without first importing them. Example:

```
if isinstance(value, (pymongo.dbref.DBRef)):
```

These will generate errors like:

```
AttributeError: 'module' object has no attribute 'dbref'
```

Pymongo does not import these modules in its root **init**.py, so how this ever worked for anyone is beyond me. Does mongoengine perhaps not support the latest pymongo?

**Comment by hmarr** [comment]
PyMongo's api changed at v1.9 - this was fixed in the v0.4 branch of MongoEngine, but not in master. As the focus has been on getting v0.4 ready for a release, 0.3 has fallen behind a bit. I've just cherry-picked the fix onto master so that should hopefully fix the issue! Hopefully v0.4 will be out the door pretty soon.

**Comment by agronholm** [comment]
Good to know. Is API incompatibility also causing DecimalFields not to work? I get an exception from bson, claiming that it can't encode a Decimal.

**Comment by agronholm** [comment]
Ah, I see this bug has already been fixed in master. I tested the latest master and everything seems to work fine, except for two failed unit tests (index related). I hope 0.4 comes around soon.

**Comment by hmarr** [comment]
Depending on how documentation writing goes, it could be today!
